FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Backend/OrdersAPI/OrdersAPI.csproj", "OrdersAPI/"]
RUN dotnet restore "OrdersAPI/OrdersAPI.csproj"
COPY ./Backend .
WORKDIR "/src/OrdersAPI"
RUN dotnet build "OrdersAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OrdersAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OrdersAPI.dll"]
