CREATE TABLE IF NOT EXISTS public."Orders"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "SenderCity" text COLLATE pg_catalog."default" NOT NULL,
    "SenderAddress" text COLLATE pg_catalog."default" NOT NULL,
    "RecipientCity" text COLLATE pg_catalog."default" NOT NULL,
    "RecipientAddress" text COLLATE pg_catalog."default" NOT NULL,
    "Weight" double precision NOT NULL,
    "PickupDate" timestamp with time zone NOT NULL,
                               "OrderNumber" text COLLATE pg_catalog."default" NOT NULL,
                               CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
    )
                           WITH (
                               OIDS = FALSE
                               )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Orders"
    OWNER to postgres;